#![no_std]
#![no_main]

extern crate alloc;

use alloc::vec;
use alloc::vec::Vec;

use jam_pvm_common::{declare_service, Service};
use jam_pvm_common::jam_types::*;
use jam_pvm_common::accumulate::{accumulate_items, get_storage, set_storage};

use ark_bn254::{Bn254, Fr};
use ark_groth16::{Groth16, Proof, VerifyingKey};
use ark_serialize::CanonicalDeserialize;
use ark_snark::SNARK;

// BN254 pairing needs a bigger stack than polkavm's default (see spikes/groth16-gas).
polkavm_derive::min_stack_size!(4 * 1024 * 1024);

declare_service!(Voting);
struct Voting;

// One poll per deployment: the verifying key + eligibility root + poll id are baked
// into the blob (generated by circuits/voting). A voter submits a proof of
// membership-in-root + a nullifier; the service never sees their identity.
const VK_BYTES: &[u8] = include_bytes!("../vk.bin");
const ROOT_BYTES: &[u8] = include_bytes!("../root.bin");
const POLL_BYTES: &[u8] = include_bytes!("../poll_id.bin");

const PROOF_LEN: usize = 128; // compressed Groth16/BN254 proof
const FR_LEN: usize = 32; // compressed BN254 scalar
const OUT_LEN: usize = 1 + FR_LEN + 1; // [valid][nullifier(32)][vote]

fn invalid() -> WorkOutput {
    vec![0u8].into()
}

fn le_u64(b: &[u8]) -> u64 {
    let mut x = [0u8; 8];
    let n = core::cmp::min(8, b.len());
    x[..n].copy_from_slice(&b[..n]);
    u64::from_le_bytes(x)
}

impl Service for Voting {
    /// refine: verify the anonymous-vote proof and emit [valid][nullifier][vote].
    /// payload = proof(128) ++ nullifier(32) ++ vote(1). The proof is verified
    /// against the EMBEDDED root + poll_id (so it only counts for THIS poll) plus
    /// the submitted nullifier + vote (the circuit's other public inputs).
    fn refine(
        _core_index: CoreIndex,
        _item_index: usize,
        _service_id: ServiceId,
        payload: WorkPayload,
        _package_hash: WorkPackageHash,
    ) -> WorkOutput {
        let data = payload.take();
        if data.len() < PROOF_LEN + FR_LEN + 1 {
            return invalid();
        }
        let proof = match Proof::<Bn254>::deserialize_compressed(&data[..PROOF_LEN]) {
            Ok(p) => p,
            Err(_) => return invalid(),
        };
        let null_bytes = &data[PROOF_LEN..PROOF_LEN + FR_LEN];
        let nullifier = match Fr::deserialize_compressed(null_bytes) {
            Ok(n) => n,
            Err(_) => return invalid(),
        };
        let vote_byte = data[PROOF_LEN + FR_LEN];
        if vote_byte > 1 {
            return invalid();
        }

        // trusted, embedded
        let vk = VerifyingKey::<Bn254>::deserialize_compressed_unchecked(VK_BYTES).unwrap();
        let root = Fr::deserialize_compressed_unchecked(ROOT_BYTES).unwrap();
        let poll_id = Fr::deserialize_compressed_unchecked(POLL_BYTES).unwrap();
        let vote = Fr::from(vote_byte as u64);

        let public = vec![root, nullifier, poll_id, vote];
        let ok = Groth16::<Bn254>::verify(&vk, &public, &proof).unwrap_or(false);

        let mut out = Vec::with_capacity(OUT_LEN);
        out.push(if ok { 1u8 } else { 0u8 });
        out.extend_from_slice(null_bytes);
        out.push(vote_byte);
        out.into()
    }

    /// accumulate: read each work-item's refine output, reject a re-used nullifier
    /// (spent-nullifier registry in storage), and tally yes/no on-chain. This is
    /// where the verified vote becomes durable global state.
    fn accumulate(_slot: Slot, _service_id: ServiceId, _item_count: usize) -> Option<Hash> {
        for item in accumulate_items() {
            let rec = match item {
                AccumulateItem::WorkItem(r) => r,
                _ => continue,
            };
            let out = match rec.result {
                Ok(o) => o.0, // WorkOutput(Vec<u8>)
                Err(_) => continue,
            };
            if out.len() < OUT_LEN || out[0] != 1u8 {
                continue; // invalid / rejected vote
            }
            let null = &out[1..1 + FR_LEN];
            let vote = out[1 + FR_LEN];

            // spent-nullifier registry: "nf:" ++ nullifier
            let mut key = Vec::with_capacity(3 + FR_LEN);
            key.extend_from_slice(b"nf:");
            key.extend_from_slice(null);
            if get_storage(&key).is_some() {
                continue; // double-vote: already counted
            }
            set_storage(&key, &[1u8]).ok();

            // tally
            let tkey: &[u8] = if vote == 1 { b"yes" } else { b"no" };
            let n = get_storage(tkey).map(|v| le_u64(&v)).unwrap_or(0);
            set_storage(tkey, &(n + 1).to_le_bytes()).ok();
            let total = get_storage(b"total").map(|v| le_u64(&v)).unwrap_or(0);
            set_storage(b"total", &(total + 1).to_le_bytes()).ok();
        }
        None
    }
}
